services:
  steamcmd:
    build:
      context: .
      dockerfile: Dockerfile.steamcmd

    image: docker-strike/steamcmd

    deploy:
      replicas: 0 # This is just an intermediate image.

  hlds:
    container_name: hlds

    depends_on:
      - steamcmd

    build:
      context: .
      dockerfile: Dockerfile.hlds
      args:
        GAME: ${GAME:-cstrike}

    image: docker-strike/hlds

    command:
      [
        "-game", "${GAME:-cstrike}",
        "+ip", "${IP_ADDRESS:-0.0.0.0}",
        "+port", "${PORT:-27015}",
        "+maxplayers", "${MAX_PLAYERS:-24}",
        "+map", "${MAP:-de_dust2}",
        "+servercfgfile", "${CONFIG_FILE:-server.cfg}",
        "+hostname", "${SERVER_NAME:-Docker-Strike}",
        "-autoupdate", # do NOT auto update HLDS because it might fail.
        "-insecure" # VAC doesn't work, don't even bother.
      ]

    network_mode: bridge
    ports:
      - "${PORT:-27015}:${PORT:-27015}/udp"

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

    healthcheck:
      test: ["CMD", "pgrep", "hlds_linux"]
      interval: 30s
      timeout: 10s
      retries: 3
